public enum CurrentStatus {
    GETTING_NAME,
    GETTING_KEY,
    GETTING_CONFIRMATION,
    ASKING_FOR_START_POS,
    PROCESSING_START_POS,
    DEFINING_START_DIRECTION,
    MOVING,
    READING_MESSAGE,
    END,
}
